# Generated by Django 4.0.1 on 2022-02-19 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='room_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_num', models.IntegerField()),
                ('room_name', models.CharField(max_length=10)),
                ('room_size', models.IntegerField()),
            ],
        ),
    ]
